spring:
  cloud:
    nacos:
      discovery:
        enabled: false
    gateway:
      routes:
       - id: lab-login-service
         predicates:
           - Path=/login-api/**
         uri: http://localhost:8080
         filters:
           - StripPrefix=1
           - PrefixPath=/api/
       - id: lab-admin-service
         predicates:
           - Path=/admin-api/**
         uri: http://localhost:8080
         filters:
           - StripPrefix=1
           - PrefixPath=/api/
       - id: lab-teacher-service
         predicates:
           - Path=/teacher-api/**
         uri: http://localhost:8080
         filters:
           - StripPrefix=1
           - PrefixPath=/api/